pub(super) type MethodSpec = (&'static str, f64);

pub(super) struct TypeSpec {
    pub(super) name: &'static str,
    pub(super) length: f64,
    pub(super) statics: &'static [MethodSpec],
    pub(super) methods: &'static [MethodSpec],
    pub(super) accessors: &'static [&'static str],
}

const CALENDAR_STATIC: &[MethodSpec] = &[("from", 1.0)];
const CALENDAR_METHODS: &[MethodSpec] = &[
    ("dateAdd", 2.0),
    ("dateFromFields", 1.0),
    ("dateUntil", 2.0),
    ("day", 1.0),
    ("dayOfWeek", 1.0),
    ("dayOfYear", 1.0),
    ("daysInMonth", 1.0),
    ("daysInWeek", 1.0),
    ("daysInYear", 1.0),
    ("era", 1.0),
    ("eraYear", 1.0),
    ("fields", 1.0),
    ("inLeapYear", 1.0),
    ("mergeFields", 2.0),
    ("month", 1.0),
    ("monthCode", 1.0),
    ("monthDayFromFields", 1.0),
    ("monthsInYear", 1.0),
    ("toJSON", 0.0),
    ("toString", 0.0),
    ("weekOfYear", 1.0),
    ("year", 1.0),
    ("yearMonthFromFields", 1.0),
    ("yearOfWeek", 1.0),
];
const CALENDAR_ACCESSORS: &[&str] = &["id"];

const DURATION_STATIC: &[MethodSpec] = &[("compare", 2.0), ("from", 1.0)];
const DURATION_METHODS: &[MethodSpec] = &[
    ("abs", 0.0),
    ("add", 1.0),
    ("negated", 0.0),
    ("round", 1.0),
    ("subtract", 1.0),
    ("toJSON", 0.0),
    ("toLocaleString", 0.0),
    ("toString", 0.0),
    ("total", 1.0),
    ("valueOf", 0.0),
    ("with", 1.0),
];
const DURATION_ACCESSORS: &[&str] = &[
    "blank",
    "days",
    "hours",
    "microseconds",
    "milliseconds",
    "minutes",
    "months",
    "nanoseconds",
    "seconds",
    "sign",
    "weeks",
    "years",
];

const INSTANT_STATIC: &[MethodSpec] = &[
    ("compare", 2.0),
    ("from", 1.0),
    ("fromEpochMicroseconds", 1.0),
    ("fromEpochMilliseconds", 1.0),
    ("fromEpochNanoseconds", 1.0),
    ("fromEpochSeconds", 1.0),
];
const INSTANT_METHODS: &[MethodSpec] = &[
    ("add", 1.0),
    ("equals", 1.0),
    ("round", 1.0),
    ("since", 1.0),
    ("subtract", 1.0),
    ("toJSON", 0.0),
    ("toLocaleString", 0.0),
    ("toString", 0.0),
    ("toZonedDateTime", 1.0),
    ("toZonedDateTimeISO", 1.0),
    ("until", 1.0),
    ("valueOf", 0.0),
];
const INSTANT_ACCESSORS: &[&str] = &[
    "epochMicroseconds",
    "epochMilliseconds",
    "epochNanoseconds",
    "epochSeconds",
];

const PLAIN_DATE_STATIC: &[MethodSpec] = &[("compare", 2.0), ("from", 1.0)];
const PLAIN_DATE_METHODS: &[MethodSpec] = &[
    ("add", 1.0),
    ("equals", 1.0),
    ("getCalendar", 0.0),
    ("getISOFields", 0.0),
    ("since", 1.0),
    ("subtract", 1.0),
    ("toJSON", 0.0),
    ("toLocaleString", 0.0),
    ("toPlainDateTime", 0.0),
    ("toPlainMonthDay", 0.0),
    ("toPlainYearMonth", 0.0),
    ("toString", 0.0),
    ("toZonedDateTime", 1.0),
    ("until", 1.0),
    ("valueOf", 0.0),
    ("with", 1.0),
    ("withCalendar", 1.0),
];
const PLAIN_DATE_ACCESSORS: &[&str] = &[
    "calendarId",
    "day",
    "dayOfWeek",
    "dayOfYear",
    "daysInMonth",
    "daysInWeek",
    "daysInYear",
    "era",
    "eraYear",
    "inLeapYear",
    "month",
    "monthCode",
    "monthsInYear",
    "weekOfYear",
    "year",
    "yearOfWeek",
];

const PLAIN_TIME_STATIC: &[MethodSpec] = &[("compare", 2.0), ("from", 1.0)];
const PLAIN_TIME_METHODS: &[MethodSpec] = &[
    ("add", 1.0),
    ("equals", 1.0),
    ("getISOFields", 0.0),
    ("round", 1.0),
    ("since", 1.0),
    ("subtract", 1.0),
    ("toJSON", 0.0),
    ("toLocaleString", 0.0),
    ("toPlainDateTime", 1.0),
    ("toString", 0.0),
    ("toZonedDateTime", 1.0),
    ("until", 1.0),
    ("valueOf", 0.0),
    ("with", 1.0),
];
const PLAIN_TIME_ACCESSORS: &[&str] = &[
    "hour",
    "microsecond",
    "millisecond",
    "minute",
    "nanosecond",
    "second",
];

const PLAIN_DATE_TIME_STATIC: &[MethodSpec] = &[("compare", 2.0), ("from", 1.0)];
const PLAIN_DATE_TIME_METHODS: &[MethodSpec] = &[
    ("add", 1.0),
    ("equals", 1.0),
    ("getCalendar", 0.0),
    ("getISOFields", 0.0),
    ("round", 1.0),
    ("since", 1.0),
    ("subtract", 1.0),
    ("toJSON", 0.0),
    ("toLocaleString", 0.0),
    ("toPlainDate", 0.0),
    ("toPlainMonthDay", 0.0),
    ("toPlainTime", 0.0),
    ("toPlainYearMonth", 0.0),
    ("toString", 0.0),
    ("toZonedDateTime", 1.0),
    ("until", 1.0),
    ("valueOf", 0.0),
    ("with", 1.0),
    ("withCalendar", 1.0),
    ("withPlainDate", 1.0),
    ("withPlainTime", 0.0),
];
const PLAIN_DATE_TIME_ACCESSORS: &[&str] = &[
    "calendarId",
    "day",
    "dayOfWeek",
    "dayOfYear",
    "daysInMonth",
    "daysInWeek",
    "daysInYear",
    "era",
    "eraYear",
    "hour",
    "inLeapYear",
    "microsecond",
    "millisecond",
    "minute",
    "month",
    "monthCode",
    "monthsInYear",
    "nanosecond",
    "second",
    "weekOfYear",
    "year",
    "yearOfWeek",
];

const PLAIN_YEAR_MONTH_STATIC: &[MethodSpec] = &[("compare", 2.0), ("from", 1.0)];
const PLAIN_YEAR_MONTH_METHODS: &[MethodSpec] = &[
    ("add", 1.0),
    ("equals", 1.0),
    ("getCalendar", 0.0),
    ("getISOFields", 0.0),
    ("since", 1.0),
    ("subtract", 1.0),
    ("toJSON", 0.0),
    ("toLocaleString", 0.0),
    ("toPlainDate", 1.0),
    ("toString", 0.0),
    ("until", 1.0),
    ("valueOf", 0.0),
    ("with", 1.0),
];
const PLAIN_YEAR_MONTH_ACCESSORS: &[&str] = &[
    "calendarId",
    "daysInMonth",
    "daysInYear",
    "era",
    "eraYear",
    "inLeapYear",
    "month",
    "monthCode",
    "monthsInYear",
    "year",
];

const PLAIN_MONTH_DAY_STATIC: &[MethodSpec] = &[("from", 1.0)];
const PLAIN_MONTH_DAY_METHODS: &[MethodSpec] = &[
    ("equals", 1.0),
    ("getCalendar", 0.0),
    ("getISOFields", 0.0),
    ("toJSON", 0.0),
    ("toLocaleString", 0.0),
    ("toPlainDate", 1.0),
    ("toString", 0.0),
    ("valueOf", 0.0),
    ("with", 1.0),
];
const PLAIN_MONTH_DAY_ACCESSORS: &[&str] = &["calendarId", "day", "era", "eraYear", "monthCode"];

const TIME_ZONE_STATIC: &[MethodSpec] = &[("from", 1.0)];
const TIME_ZONE_METHODS: &[MethodSpec] = &[
    ("equals", 1.0),
    ("getInstantFor", 1.0),
    ("getNextTransition", 1.0),
    ("getOffsetNanosecondsFor", 1.0),
    ("getOffsetStringFor", 1.0),
    ("getPlainDateTimeFor", 1.0),
    ("getPossibleInstantsFor", 1.0),
    ("getPreviousTransition", 1.0),
    ("toJSON", 0.0),
    ("toString", 0.0),
];
const TIME_ZONE_ACCESSORS: &[&str] = &["id"];

const ZONED_DATE_TIME_STATIC: &[MethodSpec] = &[("compare", 2.0), ("from", 1.0)];
const ZONED_DATE_TIME_METHODS: &[MethodSpec] = &[
    ("add", 1.0),
    ("equals", 1.0),
    ("getCalendar", 0.0),
    ("getISOFields", 0.0),
    ("getTimeZone", 0.0),
    ("round", 1.0),
    ("since", 1.0),
    ("startOfDay", 0.0),
    ("subtract", 1.0),
    ("toInstant", 0.0),
    ("toJSON", 0.0),
    ("toLocaleString", 0.0),
    ("toPlainDate", 0.0),
    ("toPlainDateTime", 0.0),
    ("toPlainMonthDay", 0.0),
    ("toPlainTime", 0.0),
    ("toPlainYearMonth", 0.0),
    ("toString", 0.0),
    ("until", 1.0),
    ("valueOf", 0.0),
    ("with", 1.0),
    ("withCalendar", 1.0),
    ("withPlainDate", 1.0),
    ("withPlainTime", 0.0),
    ("withTimeZone", 1.0),
];
const ZONED_DATE_TIME_ACCESSORS: &[&str] = &[
    "calendarId",
    "day",
    "dayOfWeek",
    "dayOfYear",
    "daysInMonth",
    "daysInWeek",
    "daysInYear",
    "era",
    "eraYear",
    "epochMicroseconds",
    "epochMilliseconds",
    "epochNanoseconds",
    "epochSeconds",
    "hour",
    "hoursInDay",
    "inLeapYear",
    "microsecond",
    "millisecond",
    "minute",
    "month",
    "monthCode",
    "monthsInYear",
    "nanosecond",
    "offset",
    "offsetNanoseconds",
    "second",
    "timeZoneId",
    "weekOfYear",
    "year",
    "yearOfWeek",
];

pub(super) const NOW_METHODS: &[MethodSpec] = &[
    ("instant", 0.0),
    ("plainDate", 1.0),
    ("plainDateISO", 0.0),
    ("plainDateTime", 1.0),
    ("plainDateTimeISO", 0.0),
    ("plainTimeISO", 0.0),
    ("timeZoneId", 0.0),
    ("zonedDateTime", 1.0),
    ("zonedDateTimeISO", 0.0),
];

pub(super) const TYPES: &[TypeSpec] = &[
    TypeSpec {
        name: "Calendar",
        length: 1.0,
        statics: CALENDAR_STATIC,
        methods: CALENDAR_METHODS,
        accessors: CALENDAR_ACCESSORS,
    },
    TypeSpec {
        name: "Duration",
        length: 0.0,
        statics: DURATION_STATIC,
        methods: DURATION_METHODS,
        accessors: DURATION_ACCESSORS,
    },
    TypeSpec {
        name: "Instant",
        length: 1.0,
        statics: INSTANT_STATIC,
        methods: INSTANT_METHODS,
        accessors: INSTANT_ACCESSORS,
    },
    TypeSpec {
        name: "PlainDate",
        length: 3.0,
        statics: PLAIN_DATE_STATIC,
        methods: PLAIN_DATE_METHODS,
        accessors: PLAIN_DATE_ACCESSORS,
    },
    TypeSpec {
        name: "PlainDateTime",
        length: 3.0,
        statics: PLAIN_DATE_TIME_STATIC,
        methods: PLAIN_DATE_TIME_METHODS,
        accessors: PLAIN_DATE_TIME_ACCESSORS,
    },
    TypeSpec {
        name: "PlainMonthDay",
        length: 2.0,
        statics: PLAIN_MONTH_DAY_STATIC,
        methods: PLAIN_MONTH_DAY_METHODS,
        accessors: PLAIN_MONTH_DAY_ACCESSORS,
    },
    TypeSpec {
        name: "PlainTime",
        length: 0.0,
        statics: PLAIN_TIME_STATIC,
        methods: PLAIN_TIME_METHODS,
        accessors: PLAIN_TIME_ACCESSORS,
    },
    TypeSpec {
        name: "PlainYearMonth",
        length: 2.0,
        statics: PLAIN_YEAR_MONTH_STATIC,
        methods: PLAIN_YEAR_MONTH_METHODS,
        accessors: PLAIN_YEAR_MONTH_ACCESSORS,
    },
    TypeSpec {
        name: "TimeZone",
        length: 1.0,
        statics: TIME_ZONE_STATIC,
        methods: TIME_ZONE_METHODS,
        accessors: TIME_ZONE_ACCESSORS,
    },
    TypeSpec {
        name: "ZonedDateTime",
        length: 2.0,
        statics: ZONED_DATE_TIME_STATIC,
        methods: ZONED_DATE_TIME_METHODS,
        accessors: ZONED_DATE_TIME_ACCESSORS,
    },
];
