[workspace]
members = [
  "crates/rapidus_parser",
  "crates/rapidus_ast",
]
resolver = "2"

[workspace.dependencies]
thiserror = "^1.0.31"
rustc-hash = "^1.1.0"
log = "^0.4.20"
ecow = "^0.1.2"

[profile.release]
opt-level = 3
overflow-checks = false
debug = true
