version: 2

jobs:
  build:
    docker:
      - image: ragnaroek/kcov:v33

    working_directory: /opt/rapidus

    steps:
      - checkout
      - run:
          command: set -eux
      - run:
          command: apt-get update
      - run:
          command: apt-get install -y libgtk-3-dev libfreetype6-dev zlib1g-dev wget libssl-dev pkg-config cmake zlib1g-dev curl binutils-dev libcurl4-openssl-dev libdw-dev libiberty-dev git cmake make build-essential
      - run:
          command: |
            wget "https://static.rust-lang.org/rustup/dist/x86_64-unknown-linux-gnu/rustup-init"
            chmod +x rustup-init
            ./rustup-init -y --no-modify-path --default-toolchain nightly
            RUSTUP_HOME=~/.cargo/bin/rustup
            CARGO_HOME=~/.cargo/bin/cargo
            chmod -R a+w $RUSTUP_HOME $CARGO_HOME;
            rm rustup-init
            source ~/.cargo/env
      - run:
          name: Install llvm-6.0 and so on
          command: |
            apt-get install clang-6.0 llvm-6.0 llvm-6.0-dev opt libedit-dev build-essential make -y
            # ln -s /usr/bin/clang-6.0 /usr/bin/clang; 
            # ln -s /usr/bin/clang++-6.0 /usr/bin/clang++; 
            ln -s /usr/bin/llvm-config-6.0 /usr/bin/llvm-config;
      #- run:
      #    name: Setting up kcov
      #    command: |
      #      git clone https://github.com/SimonKagstrom/kcov
      #      cd kcov
      #      git checkout 9db5fa58986c2eae39e82580f15ba6fadb2dc906
      #      cmake .
      #      make -j
      #      make install
      - run:
          name: Test
          command: |
            export PATH=~/.cargo/bin:$PATH
            cargo test --no-run

            REPORT=$(find ./target/debug -maxdepth 1 -name 'rapidus-*' -a ! -name '*.d')
            for file in $REPORT; do  
              echo $file
              /usr/local/bin/kcov --include-pattern=rapidus/src --exclude-pattern=/.cargo ./target/cov "$file"
            done
            bash <(curl -s https://codecov.io/bash) -s ./target/cov
