[package]
name = "rapidus-core"
version = "0.1.1"
authors = ["uint256_t <maekawatoshiki@github.com>"]
edition = "2021"

[dependencies]
rapidus-lexer = { path = "../lexer" }
rapidus-parser = { path = "../parser" }
rapidus-ast = { path = "../ast" }
bitflags = "2.0"
libc = "0.2"
rand = "0.8"
#llvm-sys = "70.0.0"
ansi_term = "0.12"
nix = "0.30"
encoding = "0.2.33"
rustc-hash = "2.1"
libloading = "0.8"
chrono = "0.4.41"
stopwatch = "0.0.7"
nanbox = "0.2.0"
