[package]
name = "rapidus-repl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.21.2"
rapidus-core = { path = "../core" }
rapidus-parser = { path = "../parser" }
rustyline = "4.1.0"
