console.log('prototype <> constructor')
console.log(Object.prototype.constructor === Object)
console.log(Function.prototype.constructor === Function)
console.log(Array.prototype.constructor === Array)
console.log(Error.prototype.constructor === Error)
console.log(Date.prototype.constructor === Date)

console.log('prototype.__proto__ === Object.prototype')
console.log(Object.prototype.__proto__ === null)
console.log(Function.prototype.__proto__ === Object.prototype)
console.log(Array.prototype.__proto__ === Object.prototype)
console.log(Error.prototype.__proto__ === Object.prototype)
console.log(Date.prototype.__proto__ === Object.prototype)

console.log('constructor.__proto__ === Function.prototype')
console.log(Object.__proto__ === Function.prototype)
console.log(Function.__proto__ === Function.prototype)
console.log(Array.__proto__ === Function.prototype)
console.log(Error.__proto__ === Function.prototype)
console.log(Date.__proto__ === Function.prototype)
