[package]
name = "rapidus-parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rapidus-ast = { path = "../ast" }
ansi_term = "0.9.0"
encoding = "*"
