[package]
name = "rapidus_eval"
version = "0.1.0"
edition = "2021"

[dependencies]
rustc-hash = { workspace = true }
thiserror = { workspace = true }
log = { workspace = true }
ecow = { workspace = true }
rapidus_ast = { path = "../rapidus_ast" }
