[package]
name = "rapidus_parser"
version = "0.1.0"
edition = "2021"

[dependencies]
rustc-hash = { workspace = true }
thiserror = { workspace = true }
log = { workspace = true }
rapidus_ast = { path = "../rapidus_ast" }
ecow = "0.1.2"

[dev-dependencies]
insta = "1.31.0"
